//
//  GuestMessageDraftValidator.swift
//  Tryzub Reservations
//

import Foundation

enum GuestMessageDraftValidationResult: Equatable {
    case valid
    case blocked(String)
}

enum GuestMessageDraftValidator {
    static let maximumShortMessageLength = 320

    static func validate(
        _ draft: GuestMessageDraft,
        packet: GuestMessageDraftPacket
    ) -> GuestMessageDraftValidationResult {
        if let blocked = draft.blockedReason?.trimmingCharacters(in: .whitespacesAndNewlines),
           !blocked.isEmpty {
            return .blocked(blocked)
        }

        let corpus = [
            draft.emailSubject,
            draft.emailBody,
            draft.shortMessageBody,
            draft.safetyNote ?? "",
        ].joined(separator: " ").lowercased()

        if draft.shortMessageBody.count > maximumShortMessageLength {
            return .blocked("Short message exceeds \(maximumShortMessageLength) characters.")
        }

        for phrase in autoSendPhrases where corpus.contains(phrase) {
            return .blocked("Draft claims the message was already sent.")
        }

        for phrase in statusMutationPhrases where corpus.contains(phrase) {
            return .blocked("Draft claims the reservation status changed.")
        }

        for phrase in internalPhrases where corpus.contains(phrase) {
            return .blocked("Draft exposes internal system language.")
        }

        if packet.kind != .confirmation {
            for phrase in confirmationPhrases where corpus.contains(phrase) {
                return .blocked("Draft uses confirmation wording for a non-confirmation message.")
            }
        }

        if packet.tableName == nil {
            for phrase in tableReadyPhrases where corpus.contains(phrase) {
                if packet.kind != .tableReady {
                    return .blocked("Draft references a table assignment without a table name.")
                }
            }
            for phrase in tableGuaranteePhrases where corpus.contains(phrase) {
                return .blocked("Draft guarantees a table without a table name.")
            }
        }

        if !packet.policyHints.contains(where: { $0.lowercased().contains("deposit") || $0.lowercased().contains("payment") }) {
            for phrase in paymentPhrases where corpus.contains(phrase) {
                return .blocked("Draft mentions payment or deposit without policy support.")
            }
        }

        if containsLikelyGuestEmail(corpus) {
            return .blocked("Draft may include a guest email address.")
        }

        return .valid
    }

    // MARK: - Phrase lists

    private static let autoSendPhrases = [
        "has been sent",
        "have been sent",
        "i sent",
        "we sent",
        "message sent",
        "email sent",
        "text sent",
        "already sent",
    ]

    private static let statusMutationPhrases = [
        "has been cancelled",
        "have been cancelled",
        "has been canceled",
        "have been canceled",
        "has been seated",
        "have been seated",
        "status changed",
        "reservation changed",
    ]

    private static let internalPhrases = [
        "internal note",
        "staff note",
        "backend",
        "system status",
        "dto",
        "evidence",
        "generated by ai",
        "as an ai",
    ]

    private static let confirmationPhrases = [
        "is confirmed",
        "are confirmed",
        "reservation confirmed",
        "confirmation is complete",
    ]

    private static let tableReadyPhrases = [
        "your table is ready",
        "table is ready",
    ]

    private static let tableGuaranteePhrases = [
        "table is guaranteed",
        "table guaranteed",
        "guaranteed table",
    ]

    private static let paymentPhrases = [
        "deposit required",
        "payment required",
        "pay a deposit",
        "prepayment",
    ]

    private static func containsLikelyGuestEmail(_ corpus: String) -> Bool {
        let pattern = #"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"#
        return corpus.range(of: pattern, options: [.regularExpression, .caseInsensitive]) != nil
    }
}
