//
//  GuestMessageDraftValidator.swift
//  Tryzub Reservations
//

import Foundation

enum GuestMessageDraftValidationResult: Equatable {
    case valid
    case blocked(String)
}

enum GuestMessageDraftValidator {
    static let maximumShortMessageLength = 320

    static func validate(
        _ draft: GuestMessageDraft,
        packet: GuestMessageDraftPacket
    ) -> GuestMessageDraftValidationResult {
        if let blocked = draft.blockedReason?.trimmingCharacters(in: .whitespacesAndNewlines),
           !blocked.isEmpty {
            return .blocked(blocked)
        }

        let corpus = [
            draft.emailSubject,
            draft.emailBody,
            draft.shortMessageBody,
            draft.safetyNote ?? "",
        ].joined(separator: " ").lowercased()

        if draft.shortMessageBody.count > maximumShortMessageLength {
            return .blocked("Short message exceeds \(maximumShortMessageLength) characters.")
        }

        for phrase in autoSendPhrases where corpus.contains(phrase) {
            return .blocked("Draft claims the message was already sent.")
        }

        for phrase in statusMutationPhrases where corpus.contains(phrase) {
            return .blocked("Draft claims the reservation status changed.")
        }

        for phrase in internalPhrases where corpus.contains(phrase) {
            return .blocked("Draft exposes internal system language.")
        }

        for phrase in staffFacingPhrases where corpus.contains(phrase) {
            return .blocked("Draft addresses staff instead of the guest.")
        }

        if packet.kind != .confirmation {
            for phrase in confirmationPhrases where corpus.contains(phrase) {
                return .blocked("Draft uses confirmation wording for a non-confirmation message.")
            }
        }

        if packet.tableName == nil {
            for phrase in tableReadyPhrases where corpus.contains(phrase) {
                if packet.kind != .tableReady {
                    return .blocked("Draft references a table assignment without a table name.")
                }
            }
            for phrase in tableGuaranteePhrases where corpus.contains(phrase) {
                return .blocked("Draft guarantees a table without a table name.")
            }
        }

        if !packet.policyHints.contains(where: { $0.lowercased().contains("deposit") || $0.lowercased().contains("payment") }) {
            for phrase in paymentPhrases where corpus.contains(phrase) {
                return .blocked("Draft mentions payment or deposit without policy support.")
            }
        }

        if containsLikelyGuestEmail(corpus) {
            return .blocked("Draft may include a guest email address.")
        }

        if containsUnsupportedPhoneNumber(corpus, allowedPhone: packet.restaurantPhone) {
            return .blocked("Draft may include an unsupported phone number.")
        }

        if packet.kind == .tableReady, packet.tableName == nil, containsInventedTableNumber(corpus) {
            return .blocked("Draft invents a table number without a table name.")
        }

        return .valid
    }

    // MARK: - Phrase lists

    private static let autoSendPhrases = [
        "has been sent",
        "have been sent",
        "i sent",
        "we sent",
        "message sent",
        "email sent",
        "text sent",
        "already sent",
    ]

    private static let statusMutationPhrases = [
        "has been cancelled",
        "have been cancelled",
        "has been canceled",
        "have been canceled",
        "has been seated",
        "have been seated",
        "status changed",
        "reservation changed",
    ]

    private static let internalPhrases = [
        "internal note",
        "staff note",
        "backend",
        "system status",
        "dto",
        "evidence",
        "generated by ai",
        "as an ai",
    ]

    /// Meta / staff-addressed phrasing the model must never produce in a guest message.
    /// A guest draft addresses the guest only; "Dear staff" etc. means the model
    /// answered the wrong audience and the draft is rejected to the template.
    private static let staffFacingPhrases = [
        "dear staff",
        "dear team",
        "attention all staff",
        "attention staff",
        "hello team",
        "hi team",
        "to the staff",
        "for staff review",
        "guest communication draft",
        "here is a draft",
        "here is the draft",
        "this draft",
        "i am writing to provide",
        "we are writing to provide",
    ]

    private static let confirmationPhrases = [
        "is confirmed",
        "are confirmed",
        "reservation confirmed",
        "confirmation is complete",
    ]

    private static let tableReadyPhrases = [
        "your table is ready",
        "table is ready",
    ]

    private static let tableGuaranteePhrases = [
        "table is guaranteed",
        "table guaranteed",
        "guaranteed table",
    ]

    private static let paymentPhrases = [
        "deposit required",
        "payment required",
        "pay a deposit",
        "prepayment",
    ]

    private static func containsLikelyGuestEmail(_ corpus: String) -> Bool {
        let pattern = #"[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}"#
        return corpus.range(of: pattern, options: [.regularExpression, .caseInsensitive]) != nil
    }

    private static let formattedPhonePatterns = [
        #"(?:\+?1[-.\s]?)?\(?\d{3}\)?[-.\s]\d{3}[-.\s]\d{4}\b"#,
        #"\b\+1[-.\s]\d{3}[-.\s]\d{3}[-.\s]\d{4}\b"#,
        #"\b\d{3}[-.\s]\d{3}[-.\s]\d{4}\b"#,
        #"\b\d{3}\.\d{3}\.\d{4}\b"#,
        #"\b\d{3}\s\d{3}\s\d{4}\b"#,
    ]

    private static func containsUnsupportedPhoneNumber(_ corpus: String, allowedPhone: String?) -> Bool {
        let candidates = phoneDigitCandidates(in: corpus)
        guard !candidates.isEmpty else { return false }

        let allowedDigits = normalizedDigits(from: allowedPhone ?? "")
        if allowedDigits.isEmpty {
            return true
        }

        return candidates.contains { !isAllowedPhoneDigits($0, allowed: allowedDigits) }
    }

    private static func phoneDigitCandidates(in text: String) -> Set<String> {
        var candidates = Set<String>()

        for pattern in formattedPhonePatterns {
            guard let regex = try? NSRegularExpression(pattern: pattern, options: []) else { continue }
            let range = NSRange(text.startIndex..., in: text)

            for match in regex.matches(in: text, options: [], range: range) {
                guard let swiftRange = Range(match.range, in: text) else { continue }
                let substring = String(text[swiftRange])
                let digits = normalizedDigits(from: substring)
                if isUSPhoneDigitCount(digits.count) {
                    candidates.insert(digits)
                }
            }
        }

        for run in digitRuns(ofMinimumLength: 10, in: text) where isUSPhoneDigitCount(run.count) {
            candidates.insert(run)
        }

        return candidates
    }

    private static func isUSPhoneDigitCount(_ count: Int) -> Bool {
        count == 10 || count == 11
    }

    private static func containsInventedTableNumber(_ corpus: String) -> Bool {
        let pattern = #"\btable\s*#?\s*\d+\b"#
        return corpus.range(of: pattern, options: .regularExpression) != nil
    }

    private static func digitRuns(ofMinimumLength minimumLength: Int, in text: String) -> [String] {
        var runs: [String] = []
        var current = ""

        for character in text {
            if character.isNumber {
                current.append(character)
            } else if !current.isEmpty {
                if current.count >= minimumLength {
                    runs.append(current)
                }
                current = ""
            }
        }

        if current.count >= minimumLength {
            runs.append(current)
        }

        return runs
    }

    private static func normalizedDigits(from text: String) -> String {
        text.filter(\.isNumber)
    }

    private static func canonicalUSPhoneDigits(_ digits: String) -> String {
        if digits.count == 11, digits.hasPrefix("1") {
            return String(digits.dropFirst())
        }
        return digits
    }

    private static func isAllowedPhoneDigits(_ run: String, allowed: String) -> Bool {
        canonicalUSPhoneDigits(run) == canonicalUSPhoneDigits(allowed)
    }
}
